#!/bin/bash
# -*- ENCODING:  UTF-8 -*-
#AñadirCuentas

curl -X POST -H "Content-Type:application/json" -d '{"iban":"A321SD"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"FGSHS541", "titular":"Mouctar", "tipo":"cuentacorriente", "saldo":"5679121"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"FASHS541", "titular":"Joan", "tipo":"cuentanormal", "saldo":"5672421"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"HSVSF242", "titular":"Marc", "tipo":"cuentanormal", "saldo":"56319002"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"HSVSF242", "titular":"David", "tipo":"jubilacion", "saldo":"90015141"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"H01462", "titular":"Sandra", "tipo":"plandepensiones", "saldo":"9143242"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"HS12548", "titular":"Marcela", "tipo":"jubilacion", "saldo":"25000"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"HH22546", "titular":"Castro", "tipo":"plandepensiones", "saldo":"30000"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"FASF9874", "tiutlar":"EspañolDeCornella", "tipo":"cuentAhorro", "saldo":"200.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"FASD2104", "tiutlar":"Partida", "tipo":"cuentaNormal", "saldo":"500.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"FAST9102", "tiutlar":"Adrian", "tipo":"cuentanormal", "saldo":"25000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"FFST9201", "tiutlar":"Pepito", "tipo":"cuentaCorriente", "saldo":"31000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"FAST9302", "tiutlar":"Carla", "tipo":"cuentAhorro", "saldo":"2900.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"FFST9402", "tiutlar":"Marta", "tipo":"cuentaCorriente", "saldo":"7200.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"FAST9520", "tiutlar":"Paula", "tipo":"cuentAhorro", "saldo":"800.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"FAST9604", "tiutlar":"Laura", "tipo":"cuentaNormal", "saldo":"900.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"FAFD1254", "tiutlar":"Maria", "tipo":"cuentanormal", "saldo":"35000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"FFFD1004", "tiutlar":"Olivia", "tipo":"cuentaCorriente", "saldo":"45000.05"}' 'http://localhost:8080/cuenta/'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"FAFD3015", "tiutlar":"Pamela", "tipo":"cuentAhorro", "saldo":"15000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"FFFD8521", "tiutlar":"Jessica", "tipo":"cuentaCorriente", "saldo":"9200.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"FAFD9874", "tiutlar":"Jenny", "tipo":"cuentAhorro", "saldo":"12000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"FAFD2104", "tiutlar":"Valerie", "tipo":"cuentaNormal", "saldo":"10000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"FAFD9102", "tiutlar":"Aridana", "tipo":"cuentanormal", "saldo":"95000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"FFFD9201", "tiutlar":"Olmo", "tipo":"cuentaCorriente", "saldo":"8000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"FAFD9302", "tiutlar":"MasGusi", "tipo":"cuentAhorro", "saldo":"22100.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"FFFD9402", "tiutlar":"Guardiola", "tipo":"cuentaCorriente", "saldo":"94200.05"}' 'http://localhost:8080/cuenta/4'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"FAFD9520", "tiutlar":"David", "tipo":"cuentAhorro", "saldo":"8020.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"FAFD9604", "tiutlar":"Dominguez", "tipo":"cuentaNormal", "saldo":"9100.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MOSHS541", "titular":"Alba", "tipo":"cuentacorriente", "saldo":"5200.54"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MOSHS541", "titular":"Jordi", "tipo":"cuentanormal", "saldo":"4512.21"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MOVSF242", "titular":"Clara", "tipo":"cuentanormal", "saldo":"1200"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MOVSF242", "titular":"Robinson", "tipo":"jubilacion", "saldo":"15000"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MO1462", "titular":"Tyrese", "tipo":"plandepensiones", "saldo":"4500"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MO12548", "titular":"The Game", "tipo":"jubilacion", "saldo":"2500"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MO22546", "titular":"Wayne", "tipo":"plandepensiones", "saldo":"3000"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"ABSF9874", "tiutlar":"jorge", "tipo":"cuentAhorro", "saldo":"200.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"ABSD2104", "tiutlar":"juan", "tipo":"cuentaNormal", "saldo":"500.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"ABST9102", "tiutlar":"carles", "tipo":"cuentanormal", "saldo":"25000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"ABST9201", "tiutlar":"carlos", "tipo":"cuentaCorriente", "saldo":"31000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"ABST9302", "tiutlar":"tonto", "tipo":"cuentAhorro", "saldo":"2900.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"ABST9402", "tiutlar":"enric", "tipo":"cuentaCorriente", "saldo":"7200.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"ABST9520", "tiutlar":"alex", "tipo":"cuentAhorro", "saldo":"800.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"ABST9604", "tiutlar":"mou", "tipo":"cuentaNormal", "saldo":"900.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"BBFD1254", "tiutlar":"Maria", "tipo":"cuentanormal", "saldo":"35000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"BBFD1004", "tiutlar":"Olivia", "tipo":"cuentaCorriente", "saldo":"45000.05"}' 'http://localhost:8080/cuenta/'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"BBFD3015", "tiutlar":"Pamela", "tipo":"cuentAhorro", "saldo":"15000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"BBFD8521", "tiutlar":"Jessica", "tipo":"cuentaCorriente", "saldo":"9200.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"BBFD9874", "tiutlar":"Jenny", "tipo":"cuentAhorro", "saldo":"12000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"BBFD2104", "tiutlar":"Valerie", "tipo":"cuentaNormal", "saldo":"10000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"BBFD9102", "tiutlar":"Aridana", "tipo":"cuentanormal", "saldo":"95000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"BBFD9201", "tiutlar":"Olmo", "tipo":"cuentaCorriente", "saldo":"8000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"BBFD9302", "tiutlar":"MasGusi", "tipo":"cuentAhorro", "saldo":"22100.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"BBFD9402", "tiutlar":"Guardiola", "tipo":"cuentaCorriente", "saldo":"94200.05"}' 'http://localhost:8080/cuenta/4'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"BBFD9520", "tiutlar":"David", "tipo":"cuentAhorro", "saldo":"8020.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"BBFD9604", "tiutlar":"Dominguez", "tipo":"cuentaNormal", "saldo":"9100.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MKK12541", "titular":"Mouctar", "tipo":"cuentacorriente", "saldo":"5679121"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MKK02134", "titular":"Joan", "tipo":"cuentanormal", "saldo":"5672421"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MKK19511", "titular":"Marc", "tipo":"cuentanormal", "saldo":"56319002"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MKK12500", "titular":"David", "tipo":"jubilacion", "saldo":"90015141"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MKK12200", "titular":"Sandra", "tipo":"plandepensiones", "saldo":"9143242"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MKK12321", "titular":"Marcela", "tipo":"jubilacion", "saldo":"25000"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MNBL5210", "titular":"Castro", "tipo":"plandepensiones", "saldo":"30000"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MNBL5000", "tiutlar":"EspañolDeCornella", "tipo":"cuentAhorro", "saldo":"200.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MNBL5212", "tiutlar":"Partida", "tipo":"cuentaNormal", "saldo":"500.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MNBL5321", "tiutlar":"Adrian", "tipo":"cuentanormal", "saldo":"25000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MNBL3210", "tiutlar":"Pepito", "tipo":"cuentaCorriente", "saldo":"31000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MNBL7421", "tiutlar":"Carla", "tipo":"cuentAhorro", "saldo":"2900.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MNBL6541", "tiutlar":"Marta", "tipo":"cuentaCorriente", "saldo":"7200.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MNBL0214", "tiutlar":"Paula", "tipo":"cuentAhorro", "saldo":"800.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"AABB1451", "tiutlar":"Laura", "tipo":"cuentaNormal", "saldo":"900.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"AABB1214", "tiutlar":"Maria", "tipo":"cuentanormal", "saldo":"35000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"AABB1321", "tiutlar":"Olivia", "tipo":"cuentaCorriente", "saldo":"45000.05"}' 'http://localhost:8080/cuenta/'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"AABB1400", "tiutlar":"Pamela", "tipo":"cuentAhorro", "saldo":"15000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"AABB1302", "tiutlar":"Jessica", "tipo":"cuentaCorriente", "saldo":"9200.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"AABB1464", "tiutlar":"Jenny", "tipo":"cuentAhorro", "saldo":"12000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"AABB1911", "tiutlar":"Valerie", "tipo":"cuentaNormal", "saldo":"10000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MMNN5000", "tiutlar":"Aridana", "tipo":"cuentanormal", "saldo":"95000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MMNN5123", "tiutlar":"Olmo", "tipo":"cuentaCorriente", "saldo":"8000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MMNN5213", "tiutlar":"MasGusi", "tipo":"cuentAhorro", "saldo":"22100.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MMNN5102", "tiutlar":"Guardiola", "tipo":"cuentaCorriente", "saldo":"94200.05"}' 'http://localhost:8080/cuenta/4'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MMNN5301", "tiutlar":"David", "tipo":"cuentAhorro", "saldo":"8020.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MMNN5451", "tiutlar":"Dominguez", "tipo":"cuentaNormal", "saldo":"9100.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"MMNN5510", "titular":"Alba", "tipo":"cuentacorriente", "saldo":"5200.54"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"THUG1200", "titular":"Jordi", "tipo":"cuentanormal", "saldo":"4512.21"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"THUG1211", "titular":"Clara", "tipo":"cuentanormal", "saldo":"1200"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"THUG1222", "titular":"Robinson", "tipo":"jubilacion", "saldo":"15000"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"THUG1213", "titular":"Tyrese", "tipo":"plandepensiones", "saldo":"4500"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"THUG1214", "titular":"The Game", "tipo":"jubilacion", "saldo":"2500"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"THUG1205", "titular":"Wayne", "tipo":"plandepensiones", "saldo":"3000"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"THUG1209", "tiutlar":"jorge", "tipo":"cuentAhorro", "saldo":"200.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"AASS0011", "tiutlar":"juan", "tipo":"cuentaNormal", "saldo":"500.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"AASS1111", "tiutlar":"carles", "tipo":"cuentanormal", "saldo":"25000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"AASS1201", "tiutlar":"carlos", "tipo":"cuentaCorriente", "saldo":"31000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"AASS9011", "tiutlar":"tonto", "tipo":"cuentAhorro", "saldo":"2900.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"AASS1245", "tiutlar":"enric", "tipo":"cuentaCorriente", "saldo":"7200.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"ABST9520", "tiutlar":"alex", "tipo":"cuentAhorro", "saldo":"800.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"AASS2154", "tiutlar":"mou", "tipo":"cuentaNormal", "saldo":"900.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"SSSD1254", "tiutlar":"Maria", "tipo":"cuentanormal", "saldo":"35000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"SSSD1004", "tiutlar":"Olivia", "tipo":"cuentaCorriente", "saldo":"45000.05"}' 'http://localhost:8080/cuenta/'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"SSSD3015", "tiutlar":"Pamela", "tipo":"cuentAhorro", "saldo":"15000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"SSSD8521", "tiutlar":"Jessica", "tipo":"cuentaCorriente", "saldo":"9200.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"SSSD9874", "tiutlar":"Jenny", "tipo":"cuentAhorro", "saldo":"12000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"SSSD2104", "tiutlar":"Valerie", "tipo":"cuentaNormal", "saldo":"10000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"SSSD9102", "tiutlar":"Aridana", "tipo":"cuentanormal", "saldo":"95000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"SSSD9201", "tiutlar":"Olmo", "tipo":"cuentaCorriente", "saldo":"8000.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"SSSD9302", "tiutlar":"MasGusi", "tipo":"cuentAhorro", "saldo":"22100.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"SSSD9402", "tiutlar":"Guardiola", "tipo":"cuentaCorriente", "saldo":"94200.05"}' 'http://localhost:8080/cuenta/4'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"SSSD9520", "tiutlar":"David", "tipo":"cuentAhorro", "saldo":"8020.05"}' 'http://localhost:8080/cuenta'
curl -i -X POST -H "Content-Type:application/json" -d '{"iban":"SSSD9604", "tiutlar":"Dominguez", "tipo":"cuentaNormal", "saldo":"9100.05"}' 'http://localhost:8080/cuenta'

#ELIMINAR
curl -i -X DELETE 'http://localhost:8080/cuenta/3'
curl -i -X DELETE 'http://localhost:8080/cuenta/7'
curl -i -X DELETE 'http://localhost:8080/cuenta/13'
curl -i -X DELETE 'http://localhost:8080/cuenta/17'
curl -i -X DELETE 'http://localhost:8080/cuenta/21'
curl -i -X DELETE 'http://localhost:8080/cuenta/23'
curl -i -X DELETE 'http://localhost:8080/cuenta/31'
curl -i -X DELETE 'http://localhost:8080/cuenta/39'
curl -i -X DELETE 'http://localhost:8080/cuenta/41'
curl -i -X DELETE 'http://localhost:8080/cuenta/43'
curl -i -X DELETE 'http://localhost:8080/cuenta/47'
curl -i -X DELETE 'http://localhost:8080/cuenta/55'
curl -i -X DELETE 'http://localhost:8080/cuenta/63'
curl -i -X DELETE 'http://localhost:8080/cuenta/73'
curl -i -X DELETE 'http://localhost:8080/cuenta/87'
curl -i -X DELETE 'http://localhost:8080/cuenta/91'
curl -i -X DELETE 'http://localhost:8080/cuenta/101'
curl -i -X DELETE 'http://localhost:8080/cuenta/105'

#MODIFICAR
curl -i -X PUT -H "Content-Type:application/json" -d '{"iban":"A321S89QD", "titular":"David", "tipo":"cuentacorriente", "saldo":"50000"}' 'http://localhost:8080/cuenta/2'
curl -i -X PUT -H "Content-Type:application/json" -d '{"iban":"A32121211", "titular":"Marta", "tipo":"cuentacorriente", "saldo":"500"}' 'http://localhost:8080/cuenta/4'
curl -i -X PUT -H "Content-Type:application/json" -d '{"iban":"AMNH12451", "titular":"Oriol", "tipo":"cuentacorriente", "saldo":"8000"}' 'http://localhost:8080/cuenta/6'
curl -i -X PUT -H "Content-Type:application/json" -d '{"iban":"AKL1S89QD", "titular":"Ibra", "tipo":"cuentacorriente", "saldo":"2500"}' 'http://localhost:8080/cuenta/8'
curl -i -X PUT -H "Content-Type:application/json" -d '{"iban":"AKL121211", "titular":"Mari", "tipo":"cuentacorriente", "saldo":"1500"}' 'http://localhost:8080/cuenta/10'
curl -i -X PUT -H "Content-Type:application/json" -d '{"iban":"AKLH12451", "titular":"Gucci", "tipo":"cuentacorriente", "saldo":"1700"}' 'http://localhost:8080/cuenta/12'
curl -i -X PUT -H "Content-Type:application/json" -d '{"iban":"ALO1S89QD", "titular":"Ribas", "tipo":"cuentacorriente", "saldo":"50000"}' 'http://localhost:8080/cuenta/16'
curl -i -X PUT -H "Content-Type:application/json" -d '{"iban":"ALO121211", "titular":"Alfa", "tipo":"cuentacorriente", "saldo":"500"}' 'http://localhost:8080/cuenta/18'
curl -i -X PUT -H "Content-Type:application/json" -d '{"iban":"ALOH12451", "titular":"Beta", "tipo":"cuentacorriente", "saldo":"8000"}' 'http://localhost:8080/cuenta/22'
curl -i -X PUT -H "Content-Type:application/json" -d '{"iban":"ALO1S89QD", "titular":"Teta", "tipo":"cuentacorriente", "saldo":"2500"}' 'http://localhost:8080/cuenta/24'
curl -i -X PUT -H "Content-Type:application/json" -d '{"iban":"ALO121211", "titular":"Gamma", "tipo":"cuentacorriente", "saldo":"1500"}' 'http://localhost:8080/cuenta/26'
curl -i -X PUT -H "Content-Type:application/json" -d '{"iban":"ALOH12451", "titular":"Bartra", "tipo":"cuentacorriente", "saldo":"1700"}' 'http://localhost:8080/cuenta/30'
curl -i -X PUT -H "Content-Type:application/json" -d '{"iban":"POL121211", "titular":"mas", "tipo":"cuentacorriente", "saldo":"1500"}' 'http://localhost:8080/cuenta/40'
curl -i -X PUT -H "Content-Type:application/json" -d '{"iban":"POLH12451", "titular":"feijoo", "tipo":"cuentacorriente", "saldo":"1700"}' 'http://localhost:8080/cuenta/50'
curl -i -X PUT -H "Content-Type:application/json" -d '{"iban":"POO1S89QD", "titular":"soler", "tipo":"cuentacorriente", "saldo":"50000"}' 'http://localhost:8080/cuenta/60'
curl -i -X PUT -H "Content-Type:application/json" -d '{"iban":"POO121211", "titular":"montes", "tipo":"cuentacorriente", "saldo":"500"}' 'http://localhost:8080/cuenta/70'
curl -i -X PUT -H "Content-Type:application/json" -d '{"iban":"APOH12451", "titular":"olmo", "tipo":"cuentacorriente", "saldo":"8000"}' 'http://localhost:8080/cuenta/80'
curl -i -X PUT -H "Content-Type:application/json" -d '{"iban":"POO1S89QD", "titular":"manya", "tipo":"cuentacorriente", "saldo":"2500"}' 'http://localhost:8080/cuenta/90'
curl -i -X PUT -H "Content-Type:application/json" -d '{"iban":"APO121211", "titular":"diallo", "tipo":"cuentacorriente", "saldo":"1500"}' 'http://localhost:8080/cuenta/100'
curl -i -X PUT -H "Content-Type:application/json" -d '{"iban":"AHOH12451", "titular":"Berta", "tipo":"cuentacorriente", "saldo":"1700"}' 'http://localhost:8080/cuenta/88'



#añadir movimiento a una cuenta

curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"A", "importe":"21.34", "saldoactual":"2500"}' 'http://localhost:8080/cuenta/1/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"B", "importe":"65.34", "saldoactual":"2000"}' 'http://localhost:8080/cuenta/1/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"C", "importe":"80.34", "saldoactual":"3500"}' 'http://localhost:8080/cuenta/1/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"D", "importe":"65.34", "saldoactual":"4000"}' 'http://localhost:8080/cuenta/1/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"E", "importe":"80.34", "saldoactual":"1500"}' 'http://localhost:8080/cuenta/1/movimientos'

curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"An", "importe":"21.34", "saldoactual":"2500"}' 'http://localhost:8080/cuenta/2/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"Bm", "importe":"65.34", "saldoactual":"2000"}' 'http://localhost:8080/cuenta/2/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"Ck", "importe":"80.34", "saldoactual":"3500"}' 'http://localhost:8080/cuenta/2/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"Dl", "importe":"65.34", "saldoactual":"4000"}' 'http://localhost:8080/cuenta/2/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"Eñ", "importe":"80.34", "saldoactual":"1500"}' 'http://localhost:8080/cuenta/2/movimientos'

curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"A1", "importe":"21.34", "saldoactual":"2500"}' 'http://localhost:8080/cuenta/4/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"B1", "importe":"65.34", "saldoactual":"2000"}' 'http://localhost:8080/cuenta/4/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"C1", "importe":"80.34", "saldoactual":"3500"}' 'http://localhost:8080/cuenta/4/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"D1", "importe":"65.34", "saldoactual":"4000"}' 'http://localhost:8080/cuenta/4/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"E1", "importe":"80.34", "saldoactual":"1500"}' 'http://localhost:8080/cuenta/4/movimientos'

curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"A6", "importe":"21.34", "saldoactual":"2500"}' 'http://localhost:8080/cuenta/6/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"B6", "importe":"65.34", "saldoactual":"2000"}' 'http://localhost:8080/cuenta/6/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"C6", "importe":"80.34", "saldoactual":"3500"}' 'http://localhost:8080/cuenta/6/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"D6", "importe":"65.34", "saldoactual":"4000"}' 'http://localhost:8080/cuenta/6/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"E6", "importe":"80.34", "saldoactual":"1500"}' 'http://localhost:8080/cuenta/6/movimientos'

curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"A8", "importe":"21.34", "saldoactual":"2500"}' 'http://localhost:8080/cuenta/8/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"B8", "importe":"65.34", "saldoactual":"2000"}' 'http://localhost:8080/cuenta/8/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"C8", "importe":"80.34", "saldoactual":"3500"}' 'http://localhost:8080/cuenta/8/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"D8", "importe":"65.34", "saldoactual":"4000"}' 'http://localhost:8080/cuenta/8/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"E8", "importe":"80.34", "saldoactual":"1500"}' 'http://localhost:8080/cuenta/8/movimientos'

curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"A10", "importe":"21.34", "saldoactual":"2500"}' 'http://localhost:8080/cuenta/10/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"B10", "importe":"65.34", "saldoactual":"2000"}' 'http://localhost:8080/cuenta/10/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"C10", "importe":"80.34", "saldoactual":"3500"}' 'http://localhost:8080/cuenta/10/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"D10", "importe":"65.34", "saldoactual":"4000"}' 'http://localhost:8080/cuenta/10/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"E10", "importe":"80.34", "saldoactual":"1500"}' 'http://localhost:8080/cuenta/10/movimientos'

curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"A12", "importe":"21.34", "saldoactual":"2500"}' 'http://localhost:8080/cuenta/12/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"B12", "importe":"65.34", "saldoactual":"2000"}' 'http://localhost:8080/cuenta/12/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"C12", "importe":"80.34", "saldoactual":"3500"}' 'http://localhost:8080/cuenta/12/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"D12", "importe":"65.34", "saldoactual":"4000"}' 'http://localhost:8080/cuenta/12/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"E12", "importe":"80.34", "saldoactual":"1500"}' 'http://localhost:8080/cuenta/12/movimientos'

curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"A14", "importe":"21.34", "saldoactual":"2500"}' 'http://localhost:8080/cuenta/14/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"B14", "importe":"65.34", "saldoactual":"2000"}' 'http://localhost:8080/cuenta/14/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"C14", "importe":"80.34", "saldoactual":"3500"}' 'http://localhost:8080/cuenta/14/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"D14", "importe":"65.34", "saldoactual":"4000"}' 'http://localhost:8080/cuenta/14/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"E14", "importe":"80.34", "saldoactual":"1500"}' 'http://localhost:8080/cuenta/14/movimientos'

curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"A16", "importe":"21.34", "saldoactual":"2500"}' 'http://localhost:8080/cuenta/16/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"B16", "importe":"65.34", "saldoactual":"2000"}' 'http://localhost:8080/cuenta/16/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"C16", "importe":"80.34", "saldoactual":"3500"}' 'http://localhost:8080/cuenta/16/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"D16", "importe":"65.34", "saldoactual":"4000"}' 'http://localhost:8080/cuenta/16/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"E16", "importe":"80.34", "saldoactual":"1500"}' 'http://localhost:8080/cuenta/16/movimientos'

curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"A18", "importe":"21.34", "saldoactual":"2500"}' 'http://localhost:8080/cuenta/18/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"B18", "importe":"65.34", "saldoactual":"2000"}' 'http://localhost:8080/cuenta/18/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"C18", "importe":"80.34", "saldoactual":"3500"}' 'http://localhost:8080/cuenta/18/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"D18", "importe":"65.34", "saldoactual":"4000"}' 'http://localhost:8080/cuenta/18/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"E18", "importe":"80.34", "saldoactual":"1500"}' 'http://localhost:8080/cuenta/18/movimientos'

curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"A20", "importe":"21.34", "saldoactual":"2500"}' 'http://localhost:8080/cuenta/20/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"B20", "importe":"65.34", "saldoactual":"2000"}' 'http://localhost:8080/cuenta/20/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"C20", "importe":"80.34", "saldoactual":"3500"}' 'http://localhost:8080/cuenta/20/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"D20", "importe":"65.34", "saldoactual":"4000"}' 'http://localhost:8080/cuenta/20/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"E20", "importe":"80.34", "saldoactual":"1500"}' 'http://localhost:8080/cuenta/20/movimientos'

curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"A30", "importe":"21.34", "saldoactual":"2500"}' 'http://localhost:8080/cuenta/30/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"B30", "importe":"65.34", "saldoactual":"2000"}' 'http://localhost:8080/cuenta/30/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"C30", "importe":"80.34", "saldoactual":"3500"}' 'http://localhost:8080/cuenta/30/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"D30", "importe":"65.34", "saldoactual":"4000"}' 'http://localhost:8080/cuenta/30/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"E30", "importe":"80.34", "saldoactual":"1500"}' 'http://localhost:8080/cuenta/30/movimientos'

curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"A", "importe":"21.34", "saldoactual":"2500"}' 'http://localhost:8080/cuenta/40/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"B", "importe":"65.34", "saldoactual":"2000"}' 'http://localhost:8080/cuenta/40/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"C", "importe":"80.34", "saldoactual":"3500"}' 'http://localhost:8080/cuenta/40/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"D", "importe":"65.34", "saldoactual":"4000"}' 'http://localhost:8080/cuenta/40/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"E", "importe":"80.34", "saldoactual":"1500"}' 'http://localhost:8080/cuenta/40/movimientos'

curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"A50", "importe":"21.34", "saldoactual":"2500"}' 'http://localhost:8080/cuenta/50/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"B50", "importe":"65.34", "saldoactual":"2000"}' 'http://localhost:8080/cuenta/50/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"C50", "importe":"80.34", "saldoactual":"3500"}' 'http://localhost:8080/cuenta/50/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"D50", "importe":"65.34", "saldoactual":"4000"}' 'http://localhost:8080/cuenta/50/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"E50", "importe":"80.34", "saldoactual":"1500"}' 'http://localhost:8080/cuenta/50/movimientos'

curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"A60", "importe":"21.34", "saldoactual":"2500"}' 'http://localhost:8080/cuenta/60/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"B60", "importe":"65.34", "saldoactual":"2000"}' 'http://localhost:8080/cuenta/60/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"C60", "importe":"80.34", "saldoactual":"3500"}' 'http://localhost:8080/cuenta/60/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"D60", "importe":"65.34", "saldoactual":"4000"}' 'http://localhost:8080/cuenta/60/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"E60", "importe":"80.34", "saldoactual":"1500"}' 'http://localhost:8080/cuenta/60/movimientos'

curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"A70", "importe":"21.34", "saldoactual":"2500"}' 'http://localhost:8080/cuenta/70/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"B70", "importe":"65.34", "saldoactual":"2000"}' 'http://localhost:8080/cuenta/70/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"C70", "importe":"80.34", "saldoactual":"3500"}' 'http://localhost:8080/cuenta/70/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"D70", "importe":"65.34", "saldoactual":"4000"}' 'http://localhost:8080/cuenta/70/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"E70", "importe":"80.34", "saldoactual":"1500"}' 'http://localhost:8080/cuenta/70/movimientos'

curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"A80", "importe":"21.34", "saldoactual":"2500"}' 'http://localhost:8080/cuenta/80/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"B80", "importe":"65.34", "saldoactual":"2000"}' 'http://localhost:8080/cuenta/80/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"C80", "importe":"80.34", "saldoactual":"3500"}' 'http://localhost:8080/cuenta/80/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"D80", "importe":"65.34", "saldoactual":"4000"}' 'http://localhost:8080/cuenta/80/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"E80", "importe":"80.34", "saldoactual":"1500"}' 'http://localhost:8080/cuenta/80/movimientos'

curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"A90", "importe":"21.34", "saldoactual":"2500"}' 'http://localhost:8080/cuenta/90/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"B90", "importe":"65.34", "saldoactual":"2000"}' 'http://localhost:8080/cuenta/90/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"C90", "importe":"80.34", "saldoactual":"3500"}' 'http://localhost:8080/cuenta/90/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"D90", "importe":"65.34", "saldoactual":"4000"}' 'http://localhost:8080/cuenta/90/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"E90", "importe":"80.34", "saldoactual":"1500"}' 'http://localhost:8080/cuenta/90/movimientos'

curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"A100", "importe":"21.34", "saldoactual":"2500"}' 'http://localhost:8080/cuenta/100/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"B100", "importe":"65.34", "saldoactual":"2000"}' 'http://localhost:8080/cuenta/100/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"C100", "importe":"80.34", "saldoactual":"3500"}' 'http://localhost:8080/cuenta/100/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"D100", "importe":"65.34", "saldoactual":"4000"}' 'http://localhost:8080/cuenta/100/movimientos'
curl -i -X POST -H "Content-Type:application/json" -d '{"concepto":"E100", "importe":"80.34", "saldoactual":"1500"}' 'http://localhost:8080/cuenta/100/movimientos'




